services:
  main-app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: apps/main/Dockerfile
      tags:
        - artloupe-main-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV="development"
    volumes:
      - ./apps/main:/app/apps/main
      - /app/node_modules

  admin-app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
      tags:
        - artloupe-admin-app:latest
    ports:
      - "3001:3001" # Host port 3001 → Container port 3001
    environment:
      - NODE_ENV="development"
      - NEXT_PUBLIC_AUTH0_DOMAIN=your-auth0-domain
      - NEXT_PUBLIC_AUTH0_CLIENT_ID=your-auth0-client-id
    volumes:
      - ./apps/admin:/app/apps/admin
      - /app/node_modules

  local-ai:
    image: localai/localai:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - ./models:/models
    environment:
      - MODELS_PATH=/models